name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 모든 태그에서 실행

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC에 필요한 권한
      contents: read   # 소스코드 접근 권한

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install build dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install build twine
        
    - name: Build package
      run: python3 -m build
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true 